[project]
name = "subdomainpy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiodns>=3.4.0",
    "aiohttp>=3.12.0",
    "tqdm>=4.67.1",
    "uvloop>=0.21.0",
]
